# fly.toml app configuration file generated for fly-tts on 2024-02-25T12:38:42+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-tts'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'a100-40gb'
